version:
  build:
  desc:
web:
  readTimeout:
  writeTimeout:
  idleTimeout:
  shutdownTimeout:
  APIHost:
  debugHost:
auth:
  keysFolder:
  activeKID:
db:
  user:
  password:
  host:
  name:
  maxIdleCons:
  maxOpenCons:
  disableTLS: